'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class dbEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=dbEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Products() As DbSet(Of Product)
    Public Overridable Property ProductDemands() As DbSet(Of ProductDemand)
    Public Overridable Property RCDemands() As DbSet(Of RCDemand)
    Public Overridable Property RCItems() As DbSet(Of RCItem)
    Public Overridable Property SummaryItems() As DbSet(Of SummaryItem)

End Class
