'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RCItem
    Public Property RCItemId As Integer
    Public Property Description As String
    Public Property Capacity As Double

    Public Overridable Property RCDemands As ICollection(Of RCDemand) = New HashSet(Of RCDemand)

End Class
