'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SummaryItem
    Public Property SummaryItemId As Integer
    Public Property Description As String
    Public Property Rule As String
    Public Property Limit As Nullable(Of Double)

End Class
